### ISSUE TITLE
Can you consider linking to the official package

### ISSUE THREAD

**Issue by vonec** [nerdzlab/socialite-apple-sign-in#1]
https://socialiteproviders.netlify.app/providers/apple.html

**Comment by Marko298** [comment]
I saw you implemented it with same approach. What do you mean link?

**Comment by vonec** [comment]
there is an official socialite package, so I thought it would be good to let the users be aware of it :)

**Comment by vonec** [comment]
something similar to https://packagist.org/packages/ahilmurugesan/socialiteproviders-apple

**Comment by Marko298** [comment]
Yup, but this implementation is more robust

**Comment by vonec** [comment]
great work, i have checked your implementation, but there is a separate https://packagist.org/packages/ahilmurugesan/socialite-apple-helper package which does the client key generation that's linked already, wish you can mention about the official package somewhere :)
